Repository One-Trillion-Club/HUMATE-BackEnd, pull requests merged in 2024-08, with the labels that each got.

#56 [ACTIVITY] 동행 목록 조회 쿼리 수정
  src/main/resources/mybatis/mapper/companion/CompanionMapper.xml
Labels: ✨ feat

#57 [CHAT] Redis,Websocket 통신 구현
  build.gradle
  src/main/java/com/otclub/humate/common/config/RedisConfig.java
  src/main/java/com/otclub/humate/common/config/SecurityConfig.java
  src/main/java/com/otclub/humate/common/config/WebConfig.java
  src/main/java/com/otclub/humate/common/config/WebSocketConfig.java
  src/main/java/com/otclub/humate/common/handler/WebSocketHandler.java
  src/main/java/com/otclub/humate/common/service/RedisSubscriber.java
  src/main/java/com/otclub/humate/common/service/RedisWebSocketSessionManager.java
  src/main/java/com/otclub/humate/domain/chat/controller/ChatController.java
  src/main/java/com/otclub/humate/domain/chat/controller/RedisSampleController.java
  src/main/java/com/otclub/humate/domain/chat/service/RedisPubSubService.java
Labels: ✨ feat

#58 [CHAT] 메이트 맺기 API 구현
  src/main/java/com/otclub/humate/common/config/SecurityConfig.java
  src/main/java/com/otclub/humate/common/entity/ChatParticipate.java
  src/main/java/com/otclub/humate/common/exception/ErrorCode.java
  src/main/java/com/otclub/humate/common/service/MessagePublisher.java
  src/main/java/com/otclub/humate/common/service/RedisPublisher.java
  src/main/java/com/otclub/humate/common/service/RedisSubscriber.java
  src/main/java/com/otclub/humate/domain/chat/controller/MateController.java
  src/main/java/com/otclub/humate/domain/chat/dto/ChatMessageRedisDTO.java
  src/main/java/com/otclub/humate/domain/chat/dto/MateCreateRequestDTO.java
  src/main/java/com/otclub/humate/domain/chat/mapper/ChatRoomMapper.java
  src/main/java/com/otclub/humate/domain/chat/mapper/MateMapper.java
  src/main/java/com/otclub/humate/domain/chat/service/ChatMessageService.java
  src/main/java/com/otclub/humate/domain/chat/service/ChatMessageServiceImpl.java
  src/main/java/com/otclub/humate/domain/chat/service/MateService.java
  src/main/java/com/otclub/humate/domain/chat/service/MateServiceImpl.java
  src/main/java/com/otclub/humate/domain/chat/service/RedisPubSubService.java
  src/main/java/com/otclub/humate/domain/chat/vo/ChatMessage.java
  src/main/java/com/otclub/humate/domain/chat/vo/MessageType.java
  src/main/java/com/otclub/humate/domain/member/mapper/MemberMapper.java
  src/main/resources/mybatis/mapper/chat/ChatMapper.xml
  src/main/resources/mybatis/mapper/chat/MateMapper.xml
  src/main/resources/mybatis/mapper/member/MemberMapper.xml
Labels: ✨ feat

#63 [ACTIVITY] S3 업로드 로직 및 동행 목록 조회 쿼리 개선
  src/main/java/com/otclub/humate/common/upload/S3Uploader.java
  src/main/resources/mybatis/mapper/activity/ActivityMapper.xml
Labels: ✨ feat

#64 [MEMBER] 회원가입 로직 다듬기
  src/main/java/com/otclub/humate/common/exception/ErrorCode.java
  src/main/java/com/otclub/humate/domain/auth/controller/AuthController.java
  src/main/java/com/otclub/humate/domain/auth/dto/PassportVerificationRequestDTO.java
  src/main/java/com/otclub/humate/domain/auth/dto/SignUpRequestDTO.java
  src/main/java/com/otclub/humate/domain/auth/service/AuthService.java
  src/main/java/com/otclub/humate/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/otclub/humate/domain/auth/util/AuthUtil.java
  src/main/resources/application.yml
  src/main/resources/mybatis/mapper/member/MemberMapper.xml
Labels: ✨ feat

#68 [ACTIVITY] 활동 목록 반환 데이터 및 로직 개선
  src/main/java/com/otclub/humate/domain/activity/dto/CompanionActivityHistoryDetailsResponseDTO.java
  src/main/java/com/otclub/humate/domain/activity/dto/CompanionInfoDTO.java
  src/main/java/com/otclub/humate/domain/activity/dto/MissionResponseDTO.java
  src/main/java/com/otclub/humate/domain/activity/service/ActivityServiceImpl.java
  src/main/java/com/otclub/humate/domain/companion/mapper/CompanionMapper.java
  src/main/resources/mybatis/mapper/companion/CompanionMapper.xml
Labels: ✨ feat

#72 [ACTIVITY] 활동, 동행, 후기 API, MEMBER 연결
  src/main/java/com/otclub/humate/common/config/SecurityConfig.java
  src/main/java/com/otclub/humate/domain/activity/controller/ActivityController.java
  src/main/java/com/otclub/humate/domain/activity/mapper/ActivityMapper.java
  src/main/java/com/otclub/humate/domain/activity/service/ActivityService.java
  src/main/java/com/otclub/humate/domain/activity/service/ActivityServiceImpl.java
  src/main/java/com/otclub/humate/domain/companion/controller/CompanionController.java
  src/main/java/com/otclub/humate/domain/companion/mapper/CompanionMapper.java
  src/main/java/com/otclub/humate/domain/companion/service/CompanionService.java
  src/main/java/com/otclub/humate/domain/companion/service/CompanionServiceImpl.java
  src/main/java/com/otclub/humate/domain/review/controller/ReviewController.java
  src/main/resources/mybatis/mapper/activity/ActivityMapper.xml
  src/main/resources/mybatis/mapper/companion/CompanionMapper.xml
Labels: ✨ feat

#78 [REVIEW] 후기 등록 시 매너 점수 반영 및 로직 프로시저로 변경
  src/main/java/com/otclub/humate/common/entity/Review.java
  src/main/java/com/otclub/humate/domain/review/dto/ReviewRequestDTO.java
  src/main/java/com/otclub/humate/domain/review/mapper/ReviewMapper.java
  src/main/java/com/otclub/humate/domain/review/service/ReviewServiceImpl.java
  src/main/resources/mybatis/mapper/review/ReviewMapper.xml
Labels: ✨ feat

#79 [CHAT] 웹소켓 세션 관리 및 채팅방 생성 추가 작업
  .gitignore
  src/main/java/com/otclub/humate/common/config/RedisConfig.java
  src/main/java/com/otclub/humate/common/entity/ChatParticipate.java
  src/main/java/com/otclub/humate/common/handler/WebSocketHandler.java
  src/main/java/com/otclub/humate/common/service/MessagePublisher.java
  src/main/java/com/otclub/humate/common/service/RedisPubSubService.java
  src/main/java/com/otclub/humate/common/service/RedisPublisher.java
  src/main/java/com/otclub/humate/common/service/RedisSubscriber.java
  src/main/java/com/otclub/humate/common/service/RedisWebSocketSessionManager.java
  src/main/java/com/otclub/humate/domain/chat/controller/ChatRoomController.java
  src/main/java/com/otclub/humate/domain/chat/dto/ChatMessageRedisDTO.java
  src/main/java/com/otclub/humate/domain/chat/dto/ChatMessageRequestDTO.java
  src/main/java/com/otclub/humate/domain/chat/dto/ChatRoomCreateResponseDTO.java
  src/main/java/com/otclub/humate/domain/chat/dto/MateUpdateRequestDTO.java
  src/main/java/com/otclub/humate/domain/chat/mapper/ChatRoomMapper.java
  src/main/java/com/otclub/humate/domain/chat/service/ChatMessageService.java
  src/main/java/com/otclub/humate/domain/chat/service/ChatMessageServiceImpl.java
  src/main/java/com/otclub/humate/domain/chat/service/ChatRoomService.java
  src/main/java/com/otclub/humate/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/otclub/humate/domain/chat/service/MateServiceImpl.java
  src/main/java/com/otclub/humate/domain/chat/service/RedisPubSubService.java
  src/main/java/com/otclub/humate/domain/chat/vo/ChatMessage.java
  src/main/resources/application.yml
  src/main/resources/mybatis/mapper/chat/ChatRoomMapper.xml
  src/main/resources/mybatis/mapper/chat/MateMapper.xml
Labels: ✨ feat

#83 [ACTIVITY] 후기 등록 시 파일 max size 설정 변경
  src/main/resources/application.yml
Labels: ✨ feat

#86 [CHAT] MongoDB 엔티티 변수 타입 createdAt long으로 변경
  src/main/java/com/otclub/humate/common/service/RedisPubSubService.java
  src/main/java/com/otclub/humate/domain/chat/vo/ChatMessage.java
Labels: ✨ feat

#89 [ACTIVITY] 활동 검증 쿼리 개선 및 S3 Upload 비동기 처리
  src/main/java/com/otclub/humate/common/config/AsyncConfig.java
  src/main/java/com/otclub/humate/common/exception/ErrorCode.java
  src/main/java/com/otclub/humate/common/upload/S3Uploader.java
  src/main/java/com/otclub/humate/domain/activity/mapper/ActivityMapper.java
  src/main/java/com/otclub/humate/domain/activity/service/ActivityServiceImpl.java
  src/main/java/com/otclub/humate/domain/companion/dto/CompanionDetailsDTO.java
  src/main/java/com/otclub/humate/domain/companion/dto/CompanionResponseDTO.java
  src/main/resources/mybatis/mapper/activity/ActivityMapper.xml
  src/main/resources/mybatis/mapper/companion/CompanionMapper.xml
Labels: ✨ feat

#93 [ACTIVITY] 미션 제목 내용 다국어 처리
  src/main/java/com/otclub/humate/common/config/AsyncConfig.java
  src/main/java/com/otclub/humate/common/entity/Activity.java
  src/main/java/com/otclub/humate/common/entity/CompanionActivityHistory.java
  src/main/java/com/otclub/humate/common/exception/ErrorCode.java
  src/main/java/com/otclub/humate/domain/activity/controller/ActivityController.java
  src/main/java/com/otclub/humate/domain/activity/dto/ClearedMissionDTO.java
  src/main/java/com/otclub/humate/domain/activity/dto/CompanionActivityHistoryDetailsResponseDTO.java
  src/main/java/com/otclub/humate/domain/activity/dto/NewMissionDTO.java
  src/main/java/com/otclub/humate/domain/activity/service/ActivityService.java
  src/main/java/com/otclub/humate/domain/activity/service/ActivityServiceImpl.java
  src/main/java/com/otclub/humate/domain/chat/dto/ChatRoomRequestDTO.java
  src/main/java/com/otclub/humate/domain/chat/mapper/ChatRoomMapper.java
  src/main/java/com/otclub/humate/domain/companion/controller/CompanionController.java
  src/main/java/com/otclub/humate/domain/companion/dto/CompanionDTO.java
  src/main/java/com/otclub/humate/domain/companion/mapper/CompanionMapper.java
  src/main/java/com/otclub/humate/domain/companion/service/CompanionService.java
  src/main/java/com/otclub/humate/domain/companion/service/CompanionServiceImpl.java
  src/main/resources/mybatis/mapper/activity/ActivityMapper.xml
  src/main/resources/mybatis/mapper/chat/ChatRoomMapper.xml
  src/main/resources/mybatis/mapper/companion/CompanionMapper.xml
Labels: ✨ feat

#95 [CHAT] WebSocket 필터 제거, 동행되면 isMatched 값 바꾸기, 채팅방 생성 시 글 정보 넣어주기
  src/main/java/com/otclub/humate/common/config/SecurityConfig.java
  src/main/java/com/otclub/humate/common/entity/ChatRoom.java
  src/main/java/com/otclub/humate/domain/chat/controller/ChatRoomController.java
  src/main/java/com/otclub/humate/domain/chat/dto/ChatMessageRedisDTO.java
  src/main/java/com/otclub/humate/domain/chat/dto/ChatRoomCreateRequestDTO.java
  src/main/java/com/otclub/humate/domain/chat/dto/ChatRoomDetailResponseDTO.java
  src/main/java/com/otclub/humate/domain/chat/mapper/ChatRoomMapper.java
  src/main/java/com/otclub/humate/domain/chat/service/ChatRoomService.java
  src/main/java/com/otclub/humate/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/otclub/humate/domain/chat/service/MateServiceImpl.java
  src/main/java/com/otclub/humate/domain/companion/controller/CompanionController.java
  src/main/java/com/otclub/humate/domain/companion/service/CompanionServiceImpl.java
  src/main/java/com/otclub/humate/domain/mate/mapper/PostMapper.java
  src/main/resources/mybatis/mapper/chat/ChatRoomMapper.xml
  src/main/resources/mybatis/mapper/mate/PostMapper.xml
  src/test/java/com/otclub/humate/domain/chat/service/ChatRoomServiceTest.java
Labels: bug, enhancement, ✨ feat

#99 [CHAT] 소켓 통신 때 채팅 상세 데이터 담기
  src/main/java/com/otclub/humate/common/service/RedisSubscriber.java
  src/main/java/com/otclub/humate/domain/chat/controller/ChatController.java
  src/main/java/com/otclub/humate/domain/chat/controller/ChatRoomController.java
  src/main/java/com/otclub/humate/domain/chat/dto/ChatMessageWebSocketResponseDTO.java
  src/main/java/com/otclub/humate/domain/chat/dto/ChatRoomDetailDTO.java
  src/main/java/com/otclub/humate/domain/chat/mapper/ChatRoomMapper.java
  src/main/java/com/otclub/humate/domain/chat/service/ChatRoomService.java
  src/main/java/com/otclub/humate/domain/chat/service/ChatRoomServiceImpl.java
  src/main/resources/mybatis/mapper/chat/ChatRoomMapper.xml
Labels: ✨ feat

#104 [ACTIVITY] 클래스 및 메서드 주석 추가
  src/main/java/com/otclub/humate/common/config/AsyncConfig.java
  src/main/java/com/otclub/humate/common/config/S3Config.java
  src/main/java/com/otclub/humate/common/entity/Activity.java
  src/main/java/com/otclub/humate/common/entity/Companion.java
  src/main/java/com/otclub/humate/common/entity/CompanionActivityHistory.java
  src/main/java/com/otclub/humate/common/entity/CompanionActivityImg.java
  src/main/java/com/otclub/humate/common/entity/Review.java
  src/main/java/com/otclub/humate/common/exception/CustomException.java
  src/main/java/com/otclub/humate/common/exception/ErrorCode.java
  src/main/java/com/otclub/humate/common/exception/ErrorResponse.java
  src/main/java/com/otclub/humate/common/exception/GlobalExceptionHandler.java
  src/main/java/com/otclub/humate/common/upload/S3Uploader.java
  src/main/java/com/otclub/humate/domain/activity/controller/ActivityController.java
  src/main/java/com/otclub/humate/domain/activity/dto/ClearedMissionDTO.java
  src/main/java/com/otclub/humate/domain/activity/dto/CompanionActivityHistoryDetailsResponseDTO.java
  src/main/java/com/otclub/humate/domain/activity/dto/CompanionInfoDTO.java
  src/main/java/com/otclub/humate/domain/activity/dto/MissionResponseDTO.java
  src/main/java/com/otclub/humate/domain/activity/dto/NewMissionDTO.java
  src/main/java/com/otclub/humate/domain/activity/dto/UploadActivityRequestDTO.java
  src/main/java/com/otclub/humate/domain/activity/mapper/ActivityMapper.java
  src/main/java/com/otclub/humate/domain/activity/service/ActivityService.java
  src/main/java/com/otclub/humate/domain/activity/service/ActivityServiceImpl.java
  src/main/java/com/otclub/humate/domain/companion/controller/CompanionController.java
  src/main/java/com/otclub/humate/domain/companion/dto/CompanionDTO.java
  src/main/java/com/otclub/humate/domain/companion/dto/CompanionDetailsDTO.java
  src/main/java/com/otclub/humate/domain/companion/dto/CompanionPostDTO.java
  src/main/java/com/otclub/humate/domain/companion/dto/CompanionResponseDTO.java
  src/main/java/com/otclub/humate/domain/companion/mapper/CompanionMapper.java
  src/main/java/com/otclub/humate/domain/companion/service/CompanionService.java
  src/main/java/com/otclub/humate/domain/companion/service/CompanionServiceImpl.java
  src/main/java/com/otclub/humate/domain/companion/vo/CompanionStatus.java
  src/main/java/com/otclub/humate/domain/review/controller/ReviewController.java
  src/main/java/com/otclub/humate/domain/review/dto/ReviewRequestDTO.java
  src/main/java/com/otclub/humate/domain/review/dto/ReviewResponseDTO.java
  src/main/java/com/otclub/humate/domain/review/mapper/ReviewMapper.java
  src/main/java/com/otclub/humate/domain/review/service/ReviewService.java
  src/main/java/com/otclub/humate/domain/review/service/ReviewServiceImpl.java
  src/main/resources/mybatis/mapper/activity/ActivityMapper.xml
  src/main/resources/mybatis/mapper/companion/CompanionMapper.xml
  src/main/resources/mybatis/mapper/review/ReviewMapper.xml
Labels: documentation

#108 [MEMBER] 코드 주석 처리
  src/main/java/com/otclub/humate/common/config/SecurityConfig.java
  src/main/java/com/otclub/humate/common/dto/CommonResponseDTO.java
  src/main/java/com/otclub/humate/common/entity/Member.java
  src/main/java/com/otclub/humate/common/service/SmsService.java
  src/main/java/com/otclub/humate/domain/auth/controller/AuthController.java
  src/main/java/com/otclub/humate/domain/auth/dto/GeneratePhoneVerificationCodeRequestDTO.java
  src/main/java/com/otclub/humate/domain/auth/dto/LogInRequestDTO.java
  src/main/java/com/otclub/humate/domain/auth/dto/PassportVerificationRequestDTO.java
  src/main/java/com/otclub/humate/domain/auth/dto/PhoneVerificationRequestDTO.java
  src/main/java/com/otclub/humate/domain/auth/dto/SignUpRequestDTO.java
  src/main/java/com/otclub/humate/domain/auth/jwt/JwtAuthorizationFilter.java
  src/main/java/com/otclub/humate/domain/auth/jwt/JwtDTO.java
  src/main/java/com/otclub/humate/domain/auth/jwt/JwtGenerator.java
  src/main/java/com/otclub/humate/domain/auth/jwt/JwtProvider.java
  src/main/java/com/otclub/humate/domain/auth/service/AuthService.java
  src/main/java/com/otclub/humate/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/otclub/humate/domain/member/controller/MemberController.java
  src/main/java/com/otclub/humate/domain/member/dto/MateDetailResponseDTO.java
  src/main/java/com/otclub/humate/domain/member/dto/ModifyProfileRequestDTO.java
  src/main/java/com/otclub/humate/domain/member/dto/ProfileResponseDTO.java
  src/main/java/com/otclub/humate/domain/member/mapper/MemberMapper.java
  src/main/java/com/otclub/humate/domain/member/service/MemberService.java
  src/main/java/com/otclub/humate/domain/member/service/MemberServiceImpl.java
  src/main/resources/mybatis/mapper/member/MemberMapper.xml
Labels: documentation

#107 [MATE] 메이트 도메인 주석 추가
  src/main/java/com/otclub/humate/common/config/SecurityConfig.java
  src/main/java/com/otclub/humate/common/entity/Post.java
  src/main/java/com/otclub/humate/common/entity/PostPlace.java
  src/main/java/com/otclub/humate/common/entity/PostTag.java
  src/main/java/com/otclub/humate/common/entity/Tag.java
  src/main/java/com/otclub/humate/domain/mate/controller/PostController.java
  src/main/java/com/otclub/humate/domain/mate/dto/PostBasicDetailResponseDTO.java
  src/main/java/com/otclub/humate/domain/mate/dto/PostDetailResponseDTO.java
  src/main/java/com/otclub/humate/domain/mate/dto/PostListResponseDTO.java
  src/main/java/com/otclub/humate/domain/mate/dto/PostPlaceDetailResponseDTO.java
  src/main/java/com/otclub/humate/domain/mate/dto/PostPlaceRegisterRequestDTO.java
  src/main/java/com/otclub/humate/domain/mate/dto/PostRegisterRequestDTO.java
  src/main/java/com/otclub/humate/domain/mate/dto/PostSearchFilterRequestDTO.java
  src/main/java/com/otclub/humate/domain/mate/dto/PostTagDetailResponseDTO.java
  src/main/java/com/otclub/humate/domain/mate/dto/PostTagRegisterRequestDTO.java
  src/main/java/com/otclub/humate/domain/mate/mapper/PostMapper.java
  src/main/java/com/otclub/humate/domain/mate/service/PostService.java
  src/main/java/com/otclub/humate/domain/mate/service/PostServiceImpl.java
  src/main/resources/mybatis/mapper/mate/PostMapper.xml
Labels: ✨ feat
